"""All page texts in one place, so the page can be translated without
touching the code. English only, for now."""

T = {
    "title": "Kobo Hardcover Sync",
    "tagline": "Keeps your Kobo e-reader and hardcover.app in step.",
    "about": "About",
    "kobo_uploaded": "Kobo uploaded",
    "kobo_never": "No upload from the Kobo yet",
    "hc_live": "Live on Hardcover",
    "hc_dry": "Dry run, nothing goes to Hardcover",
    "books_total": "{on} of {n} books syncing",
    "never": "never",
    "sync_now": "Sync now",
    "status": "Sync status",
    # local mode
    "local_only": "This page is only for the person at this computer.",
    "local_no_key": "Open this page with `kobo-hardcover-sync open` (or from the Kobo Hardcover Sync app): it hands the browser the key for this visit.",
    "not_in_local_mode": "Not there in local mode.",
    "not_in_server_mode": "Not there in server mode.",
    "on_this_computer": "On this computer:",
    "kobo_read": "Kobo read",
    "kobo_never_local": "No Kobo plugged in yet",
    "start_steps_local": [
        "Connect to Hardcover under Settings. Nothing is sent to Hardcover until you also go live there.",
        "Plug in the Kobo. Your books appear here, all switched off, and you pick the ones that are yours.",
        "Give the collection on your Kobo a name under Settings, if you want one.",
    ],
    "s_computer": "This computer",
    "s_token_kept": "Kept in {place}.",
    "s_token_help_local": "Make an API key on Hardcover with the link below: it ticks the four permissions this tool needs (your profile name, the catalogue, reading and changing your library) and nothing more. Paste it with or without the word Bearer. It is checked with Hardcover, kept in this computer's secret store, and never shown again. It stops working on the date you choose there; you then make a new one.",
    "s_eject_on": "The Kobo is ejected after a sync that changed something",
    "s_eject_off": "The Kobo stays plugged in after a sync",
    "s_eject_turn_on": "Eject after a sync",
    "s_eject_turn_off": "Do not eject",
    "s_eject_help": "A sync that wrote the collection to the Kobo ends with a reminder to eject before unplugging. Ejecting by itself saves that step, but the Kobo then leaves Finder a few seconds after you plug it in.",
    "ok_eject_on": "The Kobo will be ejected after a sync.",
    "ok_eject_off": "The Kobo stays plugged in after a sync.",
    "not_through_proxy": "This page is only served through its sign-in proxy.",
    # settings: reading stats
    "s_stats": "Reading stats for a dashboard",
    "s_stats_off": "Off: nobody can read your stats",
    "s_stats_on": "On: readable with your stats token",
    "s_stats_make": "Make a stats token",
    "s_stats_new": "Make a new token",
    "s_stats_new_confirm": "Make a new stats token? The one in use stops working.",
    "s_stats_turn_off": "Turn off",
    "s_stats_off_confirm": "Turn the stats off? The token stops working.",
    "s_stats_token_once": "Your stats token, shown this once:",
    "s_stats_use": "Ask for /api/stats/{name} with the header Authorization: Bearer followed by the token.",
    "s_stats_help": "A small summary for a dashboard such as Home Assistant: minutes read today, this week and this month, the book you are reading and how far, and the books finished this year. No book list, nothing that can be changed. It is at /api/stats/{name}, outside the sign-in, so it needs a token of its own.",
    "ok_stats_on": "Stats token made. Copy it now: it is not shown again.",
    "ok_stats_off": "Stats turned off.",
    "disclaimer": "Kobo Hardcover Sync is an independent project. It is not affiliated with, endorsed by or sponsored by Rakuten Kobo or Hardcover.",
    "refresh": "Refresh",
    "never_synced": "Not synced yet",
    "sync_running": "Sync running",
    "last_sync": "Last sync",
    "sent": "sent",
    "planned": "planned",
    "failed": "failed",
    "adopted": "taken over from Hardcover",
    "removed": "removed on Hardcover",
    # the books page: one line under its title, and what the marks mean
    "books_meta": "{n} books from your Kobo. The Hardcover column says what the next sync does with each one.",
    "legend": "What the marks mean",
    "legend_next": "Next sync changes this",
    "legend_wait": "Nothing to send yet",
    "legend_ok": "Up to date",
    "legend_stet": "Kept as on Hardcover",
    "legend_warn": "Needs you",
    "legend_err": "Failed",
    "legend_none": "Not syncing",
    "shelf_finished": "finished {date}",
    # the first run: above the list until the reader goes live
    "fr_title": "Pick the books that are yours",
    "fr_text": "Your Kobo sent {n} books. The {h} that were on it before Kobo Hardcover Sync started begin as Off, so books someone else read on a shared Kobo account stay off your Hardcover shelf. Search for an author or a title, then switch on everything shown at once.",
    "fr_tally": "switched on so far.",
    "fr_dry": "Nothing is sent while this is a dry run.",
    "fr_steps": "Three steps",
    "fr_connect": "Connect to Hardcover",
    "fr_connect_todo": "Not yet.",
    "fr_connect_link": "Connect in Settings",
    "fr_connect_done": "Done.",
    "fr_pick": "Pick your books",
    "fr_pick_here": "You are here. Each book you switch on gets a red mark in the Hardcover column: what Hardcover would be told.",
    "fr_live": "Go live",
    "fr_live_when": "Under Settings, once the marks look right. This part of the page goes away then.",
    "fr_live_link": "Settings",
    "marked_send": ("sends {n} marked change", "sends {n} marked changes"),
    "marked_would": ("would send {n} marked change", "would send {n} marked changes"),
    # toolbar
    "search": "Search title or author",
    "sort_by": "Sort by",
    "sort_last_read": "Last read",
    "sort_author": "Author",
    "sort_title": "Title",
    "apply": "Search",
    "filter": "Filter",
    "g_progress": "Reading progress",
    "g_kobo": "On this Kobo",
    "g_hardcover": "Hardcover status",
    "f_all": "All",
    "f_reading": "Reading",
    "f_finished": "Finished",
    "f_unread": "Unread",
    "f_history": "History",
    "f_new": "New",
    "f_on": "Syncing",
    "f_off": "Not syncing",
    "f_needs_match": "Needs a match",
    "f_not_ebook": "Not an ebook",
    "set_shown": "Set all {n} shown to",
    "apply_bulk": "Set",
    "confirm_bulk": "Change sync to {mode} for all books shown ({n})?",
    "confirm_bulk_what": "Only the books in the list you were looking at change; the search and filter decide which those are. Nothing goes to Hardcover until the next sync.",
    "confirm_bulk_yes": "Change sync to {mode}",
    "cancel": "Cancel",
    "empty": "No books match.",
    "empty_reset": "Show all books",
    # columns and row
    "col_book": "Book",
    "col_mode": "Sync",
    "col_state": "State",
    "col_hardcover": "Hardcover status",
    "new_tag": "New",
    "show_cover": "Show the cover of {title} larger",
    "cover_dialog": "Book cover",
    "close": "Close",
    "on": "On",
    "off": "Off",
    "auto": "Auto",
    "kobo": "Follow Kobo",
    "finished_pin": "Finished",
    "rereading": "Re-reading",
    "want": "Want to read",
    "dnf": "Did not finish",
    "state_date": "Date",
    "finished_on": "Finished",
    "last_read": "last read",
    "not_started": "Not started",
    "read_time": "read",
    "account_time_help": "Reading time across every Kobo on the account",
    # Hardcover cell
    "how_isbn": "matched by ISBN",
    "how_search": "matched by title",
    "how_manual": "chosen by you",
    "how_hardcover": "edition chosen on Hardcover",
    "format_unknown": "Format unknown",
    "needs_match": "Needs a Hardcover match",
    "match_pending": "Match pending until the next sync",
    "next_sync": "Next sync",
    "would_send": "Would send",
    "up_to_date": "Up to date on Hardcover",
    "not_yet_sent": "Unread on the Kobo, nothing to send yet",
    "not_syncing": "Not syncing",
    "other_copy": "Hardcover follows the copy of this book you read last",
    "status_error": "Last sync failed",
    "details": "Details",
    "details_of": "Details of {title}",
    "back_to_list": "Back to the list",
    "d_section_kobo": "On the Kobo",
    "d_section_hardcover": "On Hardcover",
    "d_kobo_status": "Kobo says",
    "d_unread": "Unread",
    "d_reading": "Reading",
    "d_finished": "Finished",
    "d_finished_on": "Finished on",
    "d_last_read": "Last read",
    "d_read_time": "Read time",
    "d_language": "Language",
    "d_book": "Book",
    "d_edition": "Edition",
    "d_pages": "pages",
    "d_on_shelf": "On the shelf as",
    "d_last_sync": "Last sync",
    "d_next_sync": "Next sync",
    "d_error": "Error",
    "hc_read": "Read",
    "hc_reading": "Currently reading",
    "hc_want": "Want to read",
    "hc_dnf": "Did not finish",
    "opens_hardcover": "Opens this book on Hardcover in a new tab",
    "candidates": "Hardcover candidates",
    "use": "Use",
    "no_match": "Hardcover found nothing for this book. Search for it under another title, for example the original one, or by its author.",
    "search_hc": "Search Hardcover",
    "search_hc_hint": "Other title or author",
    "search_btn": "Search",
    "remove_hc": "Remove from Hardcover",
    "confirm_remove": "Remove this book from your Hardcover shelf?",
    # errors
    "unknown_user": "Unknown user",
    "unknown_user_help": "No login arrived with this request, so Kobo Hardcover Sync cannot tell who you are. It expects to sit behind a sign-in proxy.",
    "admins_only": "This page is for admins.",
    # header
    "signed_in_as": "Signed in as",
    "nav": "Pages",
    "nav_books": "Books",
    "nav_settings": "Settings",
    "nav_admin": "Admin",
    # first visit
    "signup_title": "Welcome to Kobo Hardcover Sync",
    "signup_who": "You are signed in as {who}, and Kobo Hardcover Sync does not know you yet.",
    "signup_what": [
        "Kobo Hardcover Sync reads the reading data from your Kobo e-reader and keeps your shelf on hardcover.app in step with it: what you are reading, how far you are, and what you finished when.",
        "Starting creates your own reader here. You see only your own books, and nobody else sees yours.",
        "Nothing goes to Hardcover until you connect to it yourself and switch from dry run to live.",
    ],
    "signup_btn": "Start using Kobo Hardcover Sync",
    "start_title": "Nothing from your Kobo yet",
    "start_steps": [
        "Install Kobo Hardcover Sync on the computer you plug your Kobo into and run its setup. It prints a device hash.",
        "Add that hash under Settings, Devices.",
        "Plug in the Kobo. Your books appear here, all switched off, and you pick the ones that are yours.",
        "Connect to Hardcover under Settings to send them to your shelf.",
    ],
    "start_btn": "Open Settings",
    "hc_no_token": "Not connected to Hardcover yet: connect in Settings",
    # settings
    "settings_title": "Settings",
    "s_profile": "You",
    "s_display_name": "Name",
    "s_logins": "Logins",
    "s_reader": "Reader",
    "s_admin": "Admin",
    "save": "Save",
    "s_hardcover": "Hardcover",
    "s_token": "Hardcover token",
    "s_token_help": "Make an API key on Hardcover with the link below: it ticks the four permissions this tool needs (your profile name, the catalogue, reading and changing your library) and nothing more. Paste it with or without the word Bearer. It is checked with Hardcover, stored encrypted, and never shown again. It stops working on the date you choose there; you then make a new one.",
    "s_token_link": "Make a token on Hardcover",
    "s_token_save": "Check and save",
    "s_token_replace": "Replace the token",
    "s_connect": "Connect to Hardcover",
    "s_connect_help": "You approve on Hardcover itself: no token to make or copy. Kobo Hardcover Sync may then read your profile name, the catalogue and your library, and change your library, and nothing more. End the connection here or on Hardcover whenever you like.",
    "s_connect_open": "Open Hardcover to approve",
    "s_connect_step1": "Open Hardcover. It asks whether Kobo Hardcover Sync may use your account.",
    "s_connect_step2": "Check that it shows this code:",
    "s_connect_step3": "Approve there, then come back here.",
    "s_connect_done": "I have approved it",
    "s_connect_cancel": "Cancel",
    "s_connect_waiting": "Not approved on Hardcover yet. Approve there first.",
    "s_paste_instead": "Paste a token instead",
    "s_disconnect": "Disconnect",
    "s_disconnect_confirm": "Disconnect from Hardcover? Syncing to Hardcover stops and Kobo Hardcover Sync goes back to dry run.",
    "s_token_remove": "Remove the token",
    "s_token_remove_confirm": "Remove your Hardcover token? Syncing to Hardcover stops and Kobo Hardcover Sync goes back to dry run.",
    "tok_stored": "Token stored",
    "tok_stored_as": "Connected to Hardcover as {user}",
    "tok_none": "Not connected yet",
    "tok_unreadable": "The stored token cannot be read any more. Enter it again.",
    "tok_env": "Token set on the server by the admin",
    "tok_no_key": "Tokens cannot be stored yet: the server has no KHS_SECRET_KEY. Ask the admin.",
    "s_mode": "Sending",
    "s_live": "Live: changes go to your Hardcover shelf",
    "s_dry": "Dry run: Kobo Hardcover Sync only shows what it would send",
    "s_go_live": "Go live",
    "s_go_live_confirm": "Go live? From the next sync Kobo Hardcover Sync writes to your Hardcover shelf.",
    "s_go_dry": "Back to dry run",
    "s_collection": "Collection on the Kobo",
    "s_collection_help": "A collection with this name is kept on your Kobo, holding exactly the books you switched on. Useful on a shared Kobo account. Change the name and the old collection is replaced at the next plug-in; leave it empty and the collection is taken off the Kobo again.",
    "s_collection_name": "Collection name",
    "s_check": "Check",
    "s_check_help": "Looks at everything a sync depends on and says what to do about what is wrong. It changes nothing, and asks Hardcover one question: whose token this is.",
    "s_check_help_local": "Looks at everything a sync depends on and says what to do about what is wrong: with the Kobo plugged in, the Kobo too. It changes nothing, and asks Hardcover one question: whose token this is.",
    "s_check_btn": "Check now",
    "s_check_again": "Check again",
    "s_check_todo": "To do:",
    "s_devices": "Devices",
    "s_devices_help": "Each computer that uploads your Kobo has its own upload token. Setup on that computer (kobo-hardcover-sync setup) keeps the token there and prints its SHA-256 hash; paste the hash here. The hash alone cannot upload anything.",
    "s_no_devices": "No device yet",
    "s_device": "Device",
    "s_device_name": "Device name",
    "s_device_name_hint": "kobo-yourname",
    "s_device_hash": "Token hash (SHA-256)",
    "s_device_hash_hint": "64 characters, printed by setup",
    "s_device_added": "added",
    "s_device_last": "last upload",
    "s_device_never": "no upload yet",
    "s_device_add": "Add device",
    "s_device_remove": "Remove",
    "s_device_remove_confirm": "Remove this device? Uploads from it stop; the books it already uploaded stay.",
    "ok_profile": "Name saved.",
    "ok_token": "Hardcover accepted the token. It is stored.",
    "ok_token_removed": "Token removed. Kobo Hardcover Sync is in dry run.",
    "ok_connected": "Connected to Hardcover.",
    "ok_live": "Live. The next sync writes to Hardcover.",
    "ok_dry": "Dry run. Nothing goes to Hardcover.",
    "ok_collection": "Collection saved. The Kobo follows at its next upload.",
    "ok_device_added": "Device added. Plug in the Kobo to upload.",
    "ok_device_removed": "Device removed.",
    "ok_signed_up": "Your reader is ready. Add your Kobo below, then connect to Hardcover.",
    "ok_role": "Role changed.",
    "ok_reader_removed": "Reader removed.",
    "err_no_identity": "No login arrived with this request.",
    "err_exists": "This login already has a reader.",
    "err_name_empty": "Enter a name.",
    "err_live_needs_token": "Connect to Hardcover first.",
    "err_no_reader": "No such reader.",
    "err_last_admin": "This is the only admin. Make someone else admin first.",
    "err_no_key": "Tokens cannot be stored: the server has no KHS_SECRET_KEY.",
    "err_token_empty": "Paste your Hardcover token.",
    "err_token_refused": "The token was not stored.",
    "err_connect": "Connecting to Hardcover did not work.",
    "err_device_name": "A device name is 1 to 40 letters, digits, dashes or underscores.",
    "err_hash": "The hash is 64 characters, 0-9 and a-f. Paste the line the installer printed.",
    "err_hash_taken": "This hash is already in use.",
    # admin
    "admin_title": "Admin",
    "admin_intro": "Who uses Kobo Hardcover Sync and how their sync is doing. Books and tokens stay with each reader.",
    "a_readers": "Readers",
    "a_reader": "Reader",
    "a_logins": "Logins",
    "a_kobo": "Kobo",
    "a_hardcover": "Hardcover",
    "a_books": "Books",
    "a_actions": "Actions",
    "a_you": "you",
    "a_admin": "Admin",
    "a_devices": ("{n} device", "{n} devices"),
    "a_no_upload": "No upload yet",
    "a_uploaded": "Uploaded {when}",
    "a_live": "Live",
    "a_dry": "Dry run",
    "a_no_token": "No token",
    "a_token_unreadable": "Token unreadable",
    "a_last_sync": "last sync {when}",
    "a_never_synced": "not synced yet",
    "a_syncing": "{on} of {n} syncing",
    "a_make_admin": "Make admin",
    "a_remove_admin": "Remove admin",
    "a_remove": "Remove reader",
    "a_remove_confirm": "Remove {name} and everything Kobo Hardcover Sync holds for them: books, selection, reading minutes, snapshots, devices and token? Their Hardcover shelf is not touched. This cannot be undone.",
    "a_storage": "Storage",
    "a_database": "Database",
    "a_snapshots": "Kobo snapshots",
    "a_covers": "Covers",
    "a_problems": "Recent sync problems",
    "a_no_problems": "No failed syncs.",
    "a_books_failed": ("{n} book failed", "{n} books failed"),
    "a_only_admin": "The only admin",
    "a_key": "Token encryption",
    "a_key_ok": "Key present, tokens are stored encrypted",
    "a_key_missing": "No valid KHS_SECRET_KEY: readers cannot store a token",
    # help dialog
    "help": "Help",
    "help_title": "How Kobo Hardcover Sync works",
    # A string is a paragraph; (term, text) explains a word on the page;
    # (kind, term, text) shows the status dot of that kind before the term.
    "help_sections": [
        (
            "What this is",
            [
                "Kobo Hardcover Sync reads the reading data from your Kobo e-reader and keeps hardcover.app in step with it: which books you are reading, how far you are, and what you finished when.",
                "It also keeps your reading minutes (for a dashboard of your own, if you have one), and can put a collection with your synced books on the Kobo: handy when a Kobo account is shared and the device lists everyone's books.",
                "It does not manage books: it works with whatever is on the Kobo, books from the Kobo store included.",
            ],
        ),
        (
            "What happens when",
            [
                (
                    "Kobo plugged in",
                    "The computer with the Kobo Hardcover Sync agent uploads the Kobo's reading data here. The books you switched on are then synced to Hardcover, and the collection on the Kobo is updated.",
                ),
                ("Every hour, and on Sync now", "Changes you made on Hardcover are taken over here as well."),
                "Nothing is ever changed on the Kobo except the collection with your synced books.",
            ],
        ),
        (
            "Sync",
            [
                ("On", "This book goes to Hardcover."),
                (
                    "Off",
                    "It does not. Books that were already on the Kobo when Kobo Hardcover Sync started begin as Off, so you can pick yours.",
                ),
                ("Auto", "A book you open on this Kobo from now on syncs by itself; switch it Off if it is not yours."),
            ],
        ),
        (
            "State",
            [
                ("Follow Kobo", "Hardcover gets what the Kobo says: reading with progress, or finished."),
                ("Finished", "Counts as read on that date, even if the Kobo shows a few percent because you opened it again."),
                ("Re-reading", "A new read-through of a book you finished before."),
                ("Want to read, Did not finish", "Hardcover keeps that status and nothing is sent until you set Follow Kobo again."),
                "A status you set on Hardcover shows up here as the matching State.",
            ],
        ),
        (
            "Hardcover status",
            [
                "The Hardcover column is marked the way a proofreader marks a page: what the next sync changes, and what it leaves alone.",
                (
                    "next",
                    "Red caret",
                    "The next sync sends this. What Hardcover has now is struck through; what it gets follows the caret. In a dry run nothing is sent: the caret shows what would be.",
                ),
                ("wait", "Dashed caret", "The book is switched on but unread, so there is nothing to send yet."),
                ("ok", "Tick", "Up to date on Hardcover."),
                (
                    "stet",
                    "stet",
                    "Kept as it is on Hardcover: an edition you chose there wins over the one Kobo Hardcover Sync would pick. "
                    'Stet is Latin for "let it stand": a proofreader writes it in the margin to cancel a correction and keep the original.',
                ),
                ("warn", "Circled question mark", "The book still needs a match on Hardcover. Open Details to pick one or search."),
                ("err", "Black square", "The last sync failed for this book. Details shows the error."),
                ("none", "Dash", "Not syncing."),
                "The line under the mark is the matched book on Hardcover and its edition format. Kobo Hardcover Sync prefers ebook editions.",
            ],
        ),
        (
            "Filters",
            [
                "One filter at a time. Reading progress and On this Kobo describe the book; Hardcover status describes the sync. Needs a match and Not an ebook are the lists to work through.",
            ],
        ),
        (
            "Settings",
            [
                "Your Hardcover token, live or dry run, the collection name on your Kobo and the devices that may upload for you are under Settings. You see and change only your own.",
            ],
        ),
    ],
}
